version: "3.3"
services:

    traefik:
        hostname: traefik
        image: traefik:latest
        container_name: traefik
        restart: always
        domainname: ${DOMAINNAME}
        networks:
          - default
          - traefik_proxy
        ports:
          - "80:80"
          - "443:443"
          - "8080:8080"
        environment:
          - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
          - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
        labels:
          - "traefik.enable=true"
          - "traefik.backend=traefik"
          - "traefik.frontend.rule=Host:traefik.${DOMAINNAME}"  
          - "traefik.port=8080"
          - "traefik.docker.network=traefik_proxy"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - ${USERDIR}/docker/traefik:/etc/traefik
          - ${USERDIR}/docker/shared:/shared

    portainer:
      image: "portainer/portainer"
      container_name: portainer
      restart: always
      ports:
        - "9000:9000"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ${USERDIR}/docker/portainer/data:/data
        - ${USERDIR}/docker/shared:/shared
      environment:
        - TZ=${TZ}

    watchtower:
      container_name: watchtower
      restart: always
      image: v2tec/watchtower
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      command: --schedule "0 0 4 * * *" --cleanup

    nginx:
      container_name: nginx
      restart: unless-stopped
      image: linuxserver/nginx
      volumes:
        - ${USERDIR}/docker/nginx/config:/config
#      ports:
#        - 1080:80
#        - 1443:443
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
      networks:
        - traefik_proxy
        - default
      labels:
        - "traefik.enable=true"
        - "traefik.backend=www"
        - "traefik.frontend.rule=Host:www.${DOMAINNAME}"
        - "traefik.docker.network=traefik_proxy"
        - "traefik.port=80"

    plex:
        container_name: plex
        restart: always
        image: linuxserver/plex
        domainname: ${DOMAINNAME}
        network_mode: host
        ports:
          - "32400:32400"
          - "1900:1900/udp"
          - "3005:3005"
          - "5353:5353/udp"
          - "8324:8324"
          - "32410:32410/udp"
          - "32412:32412/udp"
          - "32413:32413/udp"
          - "32414:32414/udp"
          - "32469:32469"
        environment:
          - VERSION=docker
          - TZ=${TZ}
          - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
          - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
        volumes:
          - ${USERDIR}/docker/plex/config:/config
          - /mnt/movies:/data/movies
          - /mnt/tvshows:/data/tvshows

    nextcloud:
      container_name: nextcloud
      restart: always
      image: "nextcloud"
      links:
        - mariadb
      volumes:
        - /mnt/nextcloud:/var/www/html
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
      networks:
        - traefik_proxy
        - default
      labels:
        - "traefik.enable=true"
        - "traefik.backend=nextcloud"
        - "traefik.frontend.rule=Host:nextcloud.${DOMAINNAME}"
        - "traefik.docker.network=traefik_proxy"
        - "traefik.port=80"

    cloudflare-ddns:
       container_name: cloudflare-ddns
       hostname: cloudflare
       image: oznu/cloudflare-ddns:latest
       restart: always
       environment:
           - EMAIL=eddie.faf@googlemail.com
           - API_KEY=5a618dc97b8eea46af82f923e84dfa0dac38d
           - ZONE=eisvogelweg2.de
           - PROXIED=false

    mariadb:
       image: mariadb
       container_name: "mariadb"
       hostname: mariadb
       volumes:
           - ${USERDIR}/docker/mariadb:/var/lib/mysql
       ports:
         - target: 3306
           published: 3306
           protocol: tcp
           mode: host
       restart: always
       environment:
         - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
         - MYSQL_USER=nextcloud
         - MYSQL_DATABASE=nextcloud
         - MYSQL_PASSWORD=terror
         - PUID=${PUID}
         - PGID=${PGID}
         - TZ=${TZ}

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

