VICE_REMOTE_MONITOR = true
VICE_REU            = true
VICE_CARTRR         = cartridge/rr38p-tmp12reu.bin
VICE_PATH           = c:\Users\DKX80DG\Downloads\C64\Tools\WinVICE-3.1-x86\x64.exe
VICE_OPTS           = +confirmexit -rrbioswrite
DEFAULT_PRG         = part1

include acme.mk
